/**
 * Large pool of premium female demo hosts for the welcome-call lure.
 * Used only when no real online female hosts are available.
 * Marked source: "demo" in rotation — never claim these are live accounts.
 */

import type { WelcomePushHost } from "./types";

const CDN = (process.env.NEXT_PUBLIC_AI_HOST_CDN || "").replace(/\/$/, "");
const FALLBACK_TEASER =
  process.env.NEXT_PUBLIC_WELCOME_TEASER_URL ||
  (CDN
    ? `${CDN}/ai_aisha_welcome/teaser.mp4`
    : "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4");

function avatar(seed: string) {
  // Deterministic female-leaning portrait seeds via pravatar
  return `https://i.pravatar.cc/800?u=${encodeURIComponent(`luma-demo-f-${seed}`)}`;
}

export type DemoHostSeed = {
  id: string;
  name: string;
  age: number;
  country: string;
  flag: string;
  language: string;
  bio: string;
  interests: string[];
  level: number;
  isVip: boolean;
  isVerified: boolean;
  avatarSeed: string;
};

/** ~24 premium female demo profiles — rotate; never hardcode one forever */
export const DEMO_HOST_POOL: DemoHostSeed[] = [
  {
    id: "demo_mira",
    name: "Mira",
    age: 23,
    country: "Korea",
    flag: "🇰🇷",
    language: "Korean · English",
    bio: "Night owl · soft playlists · late chats",
    interests: ["Music", "Chill", "Coffee"],
    level: 12,
    isVip: true,
    isVerified: true,
    avatarSeed: "mira-k-23",
  },
  {
    id: "demo_sofia",
    name: "Sofia",
    age: 25,
    country: "Brazil",
    flag: "🇧🇷",
    language: "Portuguese · English",
    bio: "Dance breaks & warm energy",
    interests: ["Dance", "Fun", "Travel"],
    level: 15,
    isVip: true,
    isVerified: true,
    avatarSeed: "sofia-br-25",
  },
  {
    id: "demo_aya",
    name: "Aya",
    age: 22,
    country: "Japan",
    flag: "🇯🇵",
    language: "Japanese · English",
    bio: "Quiet vibes · language exchange",
    interests: ["Talk", "Anime", "Tea"],
    level: 9,
    isVip: false,
    isVerified: true,
    avatarSeed: "aya-jp-22",
  },
  {
    id: "demo_lina",
    name: "Lina",
    age: 24,
    country: "Turkey",
    flag: "🇹🇷",
    language: "Turkish · English",
    bio: "Warm laughs & midnight energy",
    interests: ["Party", "Live", "Fashion"],
    level: 11,
    isVip: true,
    isVerified: true,
    avatarSeed: "lina-tr-24",
  },
  {
    id: "demo_elena",
    name: "Elena",
    age: 27,
    country: "Spain",
    flag: "🇪🇸",
    language: "Spanish · English",
    bio: "Guitar loops · sunset moods",
    interests: ["Music", "Art", "Wine"],
    level: 18,
    isVip: true,
    isVerified: true,
    avatarSeed: "elena-es-27",
  },
  {
    id: "demo_noor",
    name: "Noor",
    age: 26,
    country: "UAE",
    flag: "🇦🇪",
    language: "Arabic · English",
    bio: "Stories, style, soft voice notes",
    interests: ["Style", "Chat", "Luxury"],
    level: 14,
    isVip: true,
    isVerified: true,
    avatarSeed: "noor-ae-26",
  },
  {
    id: "demo_zara",
    name: "Zara",
    age: 23,
    country: "Pakistan",
    flag: "🇵🇰",
    language: "Urdu · English",
    bio: "Sweet talks · cozy evenings",
    interests: ["Books", "Chill", "Food"],
    level: 10,
    isVip: false,
    isVerified: true,
    avatarSeed: "zara-pk-23",
  },
  {
    id: "demo_hana",
    name: "Hana",
    age: 21,
    country: "Indonesia",
    flag: "🇮🇩",
    language: "Indonesian · English",
    bio: "Smiles first · deep chats later",
    interests: ["K-pop", "Selfie", "Travel"],
    level: 8,
    isVip: false,
    isVerified: true,
    avatarSeed: "hana-id-21",
  },
  {
    id: "demo_priya",
    name: "Priya",
    age: 24,
    country: "India",
    flag: "🇮🇳",
    language: "Hindi · English",
    bio: "Bollywood energy · heartfelt talks",
    interests: ["Movies", "Dance", "Food"],
    level: 13,
    isVip: true,
    isVerified: true,
    avatarSeed: "priya-in-24",
  },
  {
    id: "demo_amira",
    name: "Amira",
    age: 25,
    country: "Morocco",
    flag: "🇲🇦",
    language: "French · Arabic · English",
    bio: "Soft voice · endless curiosity",
    interests: ["Culture", "Art", "Tea"],
    level: 11,
    isVip: false,
    isVerified: true,
    avatarSeed: "amira-ma-25",
  },
  {
    id: "demo_yuna",
    name: "Yuna",
    age: 22,
    country: "Korea",
    flag: "🇰🇷",
    language: "Korean · English",
    bio: "Beauty tips · late-night ASMR vibes",
    interests: ["Beauty", "ASMR", "K-drama"],
    level: 16,
    isVip: true,
    isVerified: true,
    avatarSeed: "yuna-kr-22",
  },
  {
    id: "demo_luna",
    name: "Luna",
    age: 23,
    country: "Mexico",
    flag: "🇲🇽",
    language: "Spanish · English",
    bio: "Moonlight chats · playful teasing",
    interests: ["Astrology", "Music", "Fun"],
    level: 12,
    isVip: true,
    isVerified: false,
    avatarSeed: "luna-mx-23",
  },
  {
    id: "demo_maya",
    name: "Maya",
    age: 26,
    country: "Thailand",
    flag: "🇹🇭",
    language: "Thai · English",
    bio: "Beach energy · gentle conversation",
    interests: ["Travel", "Yoga", "Food"],
    level: 10,
    isVip: false,
    isVerified: true,
    avatarSeed: "maya-th-26",
  },
  {
    id: "demo_sara",
    name: "Sara",
    age: 24,
    country: "Egypt",
    flag: "🇪🇬",
    language: "Arabic · English",
    bio: "Cairo nights · witty banter",
    interests: ["Comedy", "Fashion", "Chat"],
    level: 14,
    isVip: true,
    isVerified: true,
    avatarSeed: "sara-eg-24",
  },
  {
    id: "demo_nina",
    name: "Nina",
    age: 27,
    country: "Russia",
    flag: "🇷🇺",
    language: "Russian · English",
    bio: "Calm presence · thoughtful questions",
    interests: ["Books", "Cinema", "Wine"],
    level: 17,
    isVip: true,
    isVerified: true,
    avatarSeed: "nina-ru-27",
  },
  {
    id: "demo_isla",
    name: "Isla",
    age: 22,
    country: "Philippines",
    flag: "🇵🇭",
    language: "Tagalog · English",
    bio: "Sunshine smile · easy to talk to",
    interests: ["Singing", "Gaming", "Food"],
    level: 9,
    isVip: false,
    isVerified: true,
    avatarSeed: "isla-ph-22",
  },
  {
    id: "demo_aria",
    name: "Aria",
    age: 25,
    country: "Italy",
    flag: "🇮🇹",
    language: "Italian · English",
    bio: "Espresso chats · romantic playlists",
    interests: ["Music", "Fashion", "Travel"],
    level: 15,
    isVip: true,
    isVerified: true,
    avatarSeed: "aria-it-25",
  },
  {
    id: "demo_leia",
    name: "Leia",
    age: 23,
    country: "France",
    flag: "🇫🇷",
    language: "French · English",
    bio: "Paris nights · soft French accent",
    interests: ["Art", "Wine", "Cinema"],
    level: 13,
    isVip: true,
    isVerified: true,
    avatarSeed: "leia-fr-23",
  },
  {
    id: "demo_kei",
    name: "Kei",
    age: 21,
    country: "Japan",
    flag: "🇯🇵",
    language: "Japanese · English",
    bio: "Cute reactions · gaming buddy",
    interests: ["Gaming", "Anime", "Snacks"],
    level: 7,
    isVip: false,
    isVerified: false,
    avatarSeed: "kei-jp-21",
  },
  {
    id: "demo_ruby",
    name: "Ruby",
    age: 24,
    country: "USA",
    flag: "🇺🇸",
    language: "English",
    bio: "West-coast chill · real conversations",
    interests: ["Podcasts", "Fitness", "Coffee"],
    level: 11,
    isVip: false,
    isVerified: true,
    avatarSeed: "ruby-us-24",
  },
  {
    id: "demo_valentina",
    name: "Valentina",
    age: 26,
    country: "Colombia",
    flag: "🇨🇴",
    language: "Spanish · English",
    bio: "Fire & warmth · dance anytime",
    interests: ["Dance", "Latin", "Fun"],
    level: 16,
    isVip: true,
    isVerified: true,
    avatarSeed: "vale-co-26",
  },
  {
    id: "demo_chloe",
    name: "Chloe",
    age: 23,
    country: "UK",
    flag: "🇬🇧",
    language: "English",
    bio: "British humour · late-night tea",
    interests: ["Comedy", "Tea", "Series"],
    level: 10,
    isVip: false,
    isVerified: true,
    avatarSeed: "chloe-uk-23",
  },
  {
    id: "demo_mei",
    name: "Mei",
    age: 22,
    country: "China",
    flag: "🇨🇳",
    language: "Mandarin · English",
    bio: "Soft-spoken · love deep talks",
    interests: ["Art", "Tea", "Fashion"],
    level: 12,
    isVip: true,
    isVerified: true,
    avatarSeed: "mei-cn-22",
  },
  {
    id: "demo_fatima",
    name: "Fatima",
    age: 25,
    country: "Saudi Arabia",
    flag: "🇸🇦",
    language: "Arabic · English",
    bio: "Elegant presence · meaningful chat",
    interests: ["Poetry", "Style", "Chat"],
    level: 14,
    isVip: true,
    isVerified: true,
    avatarSeed: "fatima-sa-25",
  },
];

/** Alternate first names for extra variety on demo rotations */
export const ALT_FEMALE_NAMES = [
  "Mira",
  "Sofia",
  "Aya",
  "Lina",
  "Elena",
  "Noor",
  "Zara",
  "Hana",
  "Priya",
  "Amira",
  "Yuna",
  "Luna",
  "Maya",
  "Sara",
  "Nina",
  "Isla",
  "Aria",
  "Leia",
  "Kei",
  "Ruby",
  "Valentina",
  "Chloe",
  "Mei",
  "Fatima",
  "Aisha",
  "Layla",
  "Nadia",
  "Sienna",
  "Nova",
  "Camila",
] as const;

export function demoSeedToPartial(
  seed: DemoHostSeed,
): Omit<
  WelcomePushHost,
  "message" | "messageId" | "durationPreview" | "isOnline" | "source"
> {
  return {
    host_id: seed.id,
    name: seed.name,
    age: seed.age,
    avatar: avatar(seed.avatarSeed),
    ring_video_url: FALLBACK_TEASER,
    teaser_video_url: FALLBACK_TEASER,
    country: seed.country,
    flag: seed.flag,
    language: seed.language,
    bio: seed.bio,
    interests: seed.interests,
    level: seed.level,
    isVip: seed.isVip,
    isVerified: seed.isVerified,
  };
}

export { FALLBACK_TEASER };
